-- One day I'll hack this to be less blinding because I really like it
-- otherwise :)

-- require("cyberdream").setup({
--   -- Recommended - see "Configuring" below for more config options
--   transparent = true,
--   italic_comments = true,
--   hide_fillchars = true,
--   borderless_telescope = true,
--   terminal_colors = true,
--   theme = {
--     highlights = {
--       Visual = { bg = "#8e5bb1", fg = "#ffffff" },
--     },
--   },
-- })
-- vim.cmd("colorscheme cyberdream") -- set the colorscheme
