#!/usr/bin/env bash

set -eu
set -o pipefail

abspath() {
    # generate absolute path from relative path
    # $1     : relative filename
    # return : absolute path
    if [ -d "$1" ]; then
        (cd "$1"; pwd)
    elif [ -f "$1" ]; then
        if [[ $1 = /* ]]; then
            echo "$1"
        elif [[ $1 == */* ]]; then
            echo "$(cd "${1%/*}"; pwd)/${1##*/}"
        else
            echo "$(pwd)/$1"
        fi
    fi
}

readonly ARGS="$@"
readonly LONGPROGNAME=$(abspath "$0")
readonly PROGDIR="${LONGPROGNAME%/*}"     # get directory component (remove short match)
readonly PROGNAME="${LONGPROGNAME##*/}"   # get basename component (remove long match)

set -x

cd "$PROGDIR"/..
git fetch origin master
git rebase --autostash origin/master
git submodule init
git submodule update
./vundle.sh
