#!/usr/bin/env bash

set -eu
set -o pipefail

readonly PROGDIR=$(cd "${0%/*}" && pwd)

set -x

cd "$PROGDIR"/..
git fetch origin master
git rebase --autostash origin/master
git submodule init
git submodule update
./vundle.sh
